import 'package:new_app/features/patient/models/patient_model.dart';

final List<Patient> patients = [
  Patient(
    name: "John Doe",
    contactNo: "0123456789",
    whatsappNo: "0123456789",
    address: "123 Main Street",
    email: "john@example.com",
    chiefComplain: "Toothache",
    familyDisease: "Diabetes",
    otHistory: "Appendix Surgery",
    presentMedication: "Paracetamol",
    height: "5'8\"",
    weight: "70kg",
    bloodGroup: "A+",
    commonDiagnosis: "Dental cavity",
    vaccineRecord: "Tetanus, Hepatitis B",
  ),
  Patient(
    name: "Sarah Ahmed",
    contactNo: "0198765432",
    whatsappNo: "0198765432",
    address: "45 Green Road",
    email: "sarah.ahmed@mail.com",
    chiefComplain: "Headache",
    familyDisease: "Hypertension",
    otHistory: "None",
    presentMedication: "Ibuprofen",
    height: "5'5\"",
    weight: "60kg",
    bloodGroup: "B+",
    commonDiagnosis: "Migraine",
    vaccineRecord: "COVID-19, Influenza",
  ),
  Patient(
    name: "Rafiq Islam",
    contactNo: "0181234567",
    whatsappNo: "0181234567",
    address: "78 Lake View",
    email: "rafiq.i@example.com",
    chiefComplain: "Back Pain",
    familyDisease: "Arthritis",
    otHistory: "Knee Surgery",
    presentMedication: "Diclofenac",
    height: "5'10\"",
    weight: "75kg",
    bloodGroup: "O+",
    commonDiagnosis: "Lumbar disc issue",
    vaccineRecord: "Tetanus, Typhoid",
  ),
  Patient(
    name: "Meena Kumari",
    contactNo: "0175678901",
    whatsappNo: "0175678901",
    address: "22 Hill Street",
    email: "meena.kumari@xyz.com",
    chiefComplain: "Chest Pain",
    familyDisease: "Heart Disease",
    otHistory: "Gallbladder Removal",
    presentMedication: "Aspirin",
    height: "5'4\"",
    weight: "65kg",
    bloodGroup: "AB+",
    commonDiagnosis: "Angina",
    vaccineRecord: "Hepatitis B, COVID-19",
  ),
  Patient(
    name: "Tanvir Hossain",
    contactNo: "0167890123",
    whatsappNo: "0167890123",
    address: "56 Garden Avenue",
    email: "tanvirhossain@gmail.com",
    chiefComplain: "Cough and Fever",
    familyDisease: "None",
    otHistory: "None",
    presentMedication: "Antibiotics",
    height: "5'9\"",
    weight: "72kg",
    bloodGroup: "A-",
    commonDiagnosis: "Viral fever",
    vaccineRecord: "BCG, COVID-19",
  ),
];
