name: new_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  get: ^4.7.2
  shared_preferences: ^2.5.2
  hugeicons: ^0.0.7
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/lang/bn.json
    - assets/icons/
    - assets/images/
    - assets/images/temp/
    - assets/logo/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/my-rx-logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/logo/my-rx-logo.png"
  adaptive_icon_background: "#ffffff"
